### ISSUE TITLE
Замечания по восьмому блоку

### ISSUE THREAD

**Issue by testario** [killakode/killakode.github.io-klaster-site-#10]
1. Снова внутренние отступы, используемые как внешние
<img width="864" alt="изображение" src="https://github.com/killakode/killakode.github.io-klaster-site-/assets/52890557/1f90707f-1fe6-4e70-bd25-b556f43449a1">

Используй расширенный контейнер для центровки

2. Фон одной картинкой - плохая идея, блок выглядит съехавшим на широком мониторе
<img width="860" alt="изображение" src="https://github.com/killakode/killakode.github.io-klaster-site-/assets/52890557/31379667-5de6-4431-ad9a-68c3d46164bd">

3. Бесполезный флекс
<img width="702" alt="изображение" src="https://github.com/killakode/killakode.github.io-klaster-site-/assets/52890557/10ea3076-30d1-4389-9d9c-5decc7acc2b0">

4. Использование заголовка в качестве структурного блока
<img width="532" alt="изображение" src="https://github.com/killakode/killakode.github.io-klaster-site-/assets/52890557/1ae870d1-7c43-4486-8de8-6a270887c053">

**Comment by testario** [comment]
1. ОК

2. Схитрил, но не принимаю. Цвет фона должен быть задан цветом, а картинка - это вот эти три полоски

3. Не убрал флекс, он тут не нужен, тут и так все блоки друг под другом лежат

4. ОК

Дополнительно: Опять высота у блока, убрать

**Comment by killakode** [comment]
3 пункт, я вроде как убрал флек у контейнера question__number, тут flex только на question footer

**Comment by testario** [comment]
> 3 пункт, я вроде как убрал флек у контейнера question__number, тут flex только на question footer

Не убрал
<img width="820" alt="изображение" src="https://github.com/killakode/killakode.github.io-klaster-site-/assets/52890557/42d528c6-2139-4cfe-8d75-6bc53a10216d">
